kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type:NodePoet
selector:
  app: train-schedule
ports:
-protocol: TCP
 port: 8080
 nodePort: 8080
 
 ---
 
 apiVersion: extensions/v1betal
 kind: Deployment
 metadata:
   name: train-schedule-deployement
   labels:
     app: train-schedule
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: train-schedule
template:
  metadata:
    labels: 
      app: tain-schedule
spec:
  containers:
  - name: train-schedule
    input: $DOCKER_NAME:$BUILD_NUMBER
    ports:
    - containerPort: 8080

 
